# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('group', models.CharField(max_length=30)),
                ('car', models.CharField(max_length=30)),
            ],
        ),
    ]
